POST  http://localhost:3050/users/add-user HTTP/1.1
Content-Type: application/json
Accept-Language: en-us

 {
  "userId":3,
  "firstName": "B",
  "lastName": "Dore",
  "userName":"test",
  "address": "123 Main St, Cityville",
  "phone": "555-1830",
  "email": "test.doe@example.com",
  "password": "5678"
 }

###
###


POST http://localhost:3050/users/login
Content-Type: application/json
Accept-Language: en-us

{
  "userName": "test",
  "password": "5678"
}

###

PUT http://localhost:3050/users/test
Content-Type: application/json

{
  "firstName": "david",
  "lastName": "Updated Last Name",
  "userName": "test2",
  "address": "Updated Address",
  "phone": "Updated Phone",
  "email": "updated.email@example.com",
  "password": "1111"
}
###

DELETE http://localhost:3050/users/B


###
POST http://localhost:3050/therapist/add-therapist HTTP/1.1
Content-Type: application/json
Accept-Language: en-us

{
  "therapistId": 8,
  "firstName": "Michael",
  "lastName": "Brown",
  "therapistName": "mbrown",
  "address": "303 Birch St, Township",
  "phoneNumber": "555-3456",
  "email": "michael.brown@example.com",
  "licenseAndCertifications": ["CertificationF", "CertificationG"],
  "startDate": "2023-05-20",
  "hourlyRate": 130,
  "notes": "Focus on trauma recovery."
}


