POST  http://localhost:3050/users/add-user HTTP/1.1
Content-Type: application/json
Accept-Language: en-us

 {
  "userId":3,
  "firstName": "B",
  "lastName": "Dore",
  "userName":"test",
  "address": "123 Main St, Cityville",
  "phone": "555-1830",
  "email": "test.doe@example.com",
  "password": "5678"
 }

###
###


POST http://localhost:3050/users/login
Content-Type: application/json
Accept-Language: en-us

{
  "userName": "test",
  "password": "5678"
}

###

PUT http://localhost:3050/users/test
Content-Type: application/json

{
  "firstName": "david",
  "lastName": "Updated Last Name",
  "userName": "test2",
  "address": "Updated Address",
  "phone": "Updated Phone",
  "email": "updated.email@example.com",
  "password": "1111"
}
###

DELETE http://localhost:3050/users/B


###


POST http://localhost:3050/therapist/add-therapist HTTP/1.1
Content-Type: application/json
Accept-Language: en-us

{
  "therapistId": 24,
  "firstName": "Lucas",
  "lastName": "Clark",
  "therapistName": "lclark",
  "address": "123 Maple St, Smalltown",
  "phoneNumber": "555-3456",
  "email": "lucas.clark@example.com",
  "licenseAndCertifications": ["CertificationW", "CertificationX"],
  "startDate": "2021-01-10",
  "hourlyRate": 135,
  "notes": "Specializes in stress management for adolescents.",
  "daysAvailable": {
    "Sunday": true,
    "Monday": true,
    "Tuesday": true,
    "Wednesday": true,
    "Thursday": true,
    "Friday": true,
    "Saturday": true
  },
  "availabilityHours": ["10:00-13:00", "14:00-18:00"],
  "specializations": ["Adolescent Therapy", "Stress Management"]
}








